### PR TITLE
Release 15.03.26

### PR DESCRIPTION
**Pull request by gatuno1**
Release 15.03.26:
* Corrections on all the effects for PASM hub operations (zero, carry and return): CLKSET. COGID, COGINIT, COGSTOP, LOCKNEW, LOCKRET, LOCKSET, LOCKCLR. There was some missing values for carry & zero flags.
* Algorithm optimization for PropellerCPU.PinChanged() to determinate the pin state faster for DIR and OUT.
* Corrected reset events invocations, affecting pins & lock state, and logic view. Now all of them are reset effectively.
* Improvements on LogicView, to show more helpful messages on errors, labels on buttons and text boxes.
* In Plugin Editor now you can start with a default plugin template (new default) or empty window (old default style). The program recovers it from "Resource\PluginTemplate.cs.
* Updated PluginBase class structure, so all the old plugins have to be updated:
    -Constructor invocation must call Base constructor.
	-Extra parameter on OnClock() method for current clock number in tick clocks.
	-Method PresentChip() with no param, beacuse Chip reference now is included in plugin base class definition.
	-New method OnClose() is called for every plugin before closing the emulator (to perform cleanup).
* Added program settings to remember them between sessions (stored in "Gear.exe.config" file in this version): 
	-TimeFrame and TickMarkGrid on logic view.
	-LastBinary & LastPlugin on Emulator, GearDesktop & PluginEditor.
	-UpdateEachSteps to enable changes on the screen refresh rate.
	-Added "UseNoTemplate" program setting to enable load plugin editor empty (old default style).
* Changed names and tooltips on buttons "open plugin", "load plugin", "open binary" on GearDesktop & Emulator.
* Memory leaks prevention: Corrections for Disposable members in CogView, LogicView, MemoryView & PluginEditor.
* Improved general documentation of source code, including specific pages for sequence of callings for PropellerCPU.Step() and loading a plugin in memory after compilation.

### CODE REVIEW

**Comment by gatuno1** [comment]
Hello Davis:
I commited it by mistake!! I was trying to merge the files with conflicts but I had not completed and get confused about commited.
There is a way to reverse it?, because it won't compile as is, and your changes about memory management would be lost. I was working precisely on that part of the code...

**Comment by davispuh** [comment]
I see you've done some huge work, awesome :) I haven't gotten time to work on this... and I would suggest to make commits more often with smaller changes.
Anyway about this, there are 2 options, one is to simply revert these commits which will add inverse changes, so there will be these commits adding stuff and new commit removing this added stuff, this is preferred way to do if you've publicly pushed. But downside is that commit history will be ugly if there's a lot of changes, this time, there probably aren't any users who've already pulled this so we could go with 2nd option and nuke it :P
basically, create a new branch on this master with `git branch backup` just in case if it's needed. Then in this master, reset everything back to correct commit, `git reset --hard 45871257` (it will reset back to this commit 45871257), then push it here `git push upstream --force` (use `--force` only this time as it rewrites this history and that's not nice if others would have been pulled it already). Then check if everything is ok, make sure you've your own commits in some other branch and if so then `git branch -D backup`
PS. git is very powerful and you can do a lot with it, just need to learn about features :P

**Comment by gatuno1** [comment]
Davis:
Finally It prefer to analyze the changes manually, because anyway I had to add in my repository: I have apllied only half of the changes to plugins to this main repository.
But It wasn't to difficult as I though, because GIT was very useful to compare.
The main branch now compiles, and your developments of memory managements are included, along with my corrections and (half) the modifications on plugins. But, I don't know if all works OK, because I will finish the other half of plugin modification (plugin editor mainly, with loading, saving and new data in XML files and editor, with the option of separate xxxx.cs code for each plugin). Then I will test everything to make a release. I thing this 15.03.26 rel will be internal only...

**Comment by davispuh** [comment]
I see you didn't reset that merge, so you'll keep it?

**Comment by gatuno1** [comment]
Yes, finally I examine it and it was 98% well done (not as bad I though). I only fix the differences.
Now I'm working in the remaining in my branch to finish all my changes. :-)

**Pull request merged**
